"""Shared contracts and type aliases used across the project."""

from doom_agent.shared.contracts import (
    CatalogSection,
    CheckpointMetadataPayload,
    CheckpointSelection,
    CurriculumStagePayload,
    EarlyStoppingPayload,
    EvaluationActionUsagePayload,
    EvaluationHistoryEntryPayload,
    EvaluationMetricsPayload,
    EvaluationSummaryPayload,
    ExperimentIndexEntryPayload,
    ExperimentIndexPayload,
    LegacyConfigPayload,
    ProfileOverrides,
    RewardShapingPayload,
    SaveableModel,
    ScenarioOverrides,
    TrainingProfilePayload,
    TrainingRunReportPayload,
)

__all__ = [
    "CatalogSection",
    "CheckpointSelection",
    "CheckpointMetadataPayload",
    "CurriculumStagePayload",
    "EarlyStoppingPayload",
    "EvaluationActionUsagePayload",
    "EvaluationHistoryEntryPayload",
    "ExperimentIndexEntryPayload",
    "ExperimentIndexPayload",
    "EvaluationMetricsPayload",
    "EvaluationSummaryPayload",
    "LegacyConfigPayload",
    "ProfileOverrides",
    "RewardShapingPayload",
    "SaveableModel",
    "ScenarioOverrides",
    "TrainingRunReportPayload",
    "TrainingProfilePayload",
]
